" enable pathogen
call pathogen#infect()

" Display
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
colorscheme koehler                         " nicer colors
set list listchars=tab:»·,trail:·,extends:#
                                            " higlight extra whitespaces
set title                                   " change terminal title
set visualbell                              " blink on errors
syntax on                                   " enable syntax highlighting
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo,.pyc
                                            " ignore on auto completion
set so=5                                    " lines of context while scrolling
set ruler                                   " Show cursor position all the time
set foldmethod=syntax                       " fold blocks using syntax
autocmd BufEnter * setlocal cursorline      " underline current line

" Search
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set hlsearch                                " highlight search results
set is                                      " search while typing
set smartcase                               " smartcase for searching

" underline misspelled words
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
hi clear SpellBad
hi SpellBad cterm=underline,bold ctermfg=red

" mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader=","                           " set lead for custom bindings
" ,ev -> open vimrc
nmap <silent> <leader>ev :e ~/.vimrc<CR>
" while inserting toggle paste mode
set pastetoggle=<F2>
" ; also changes to command mode
nnoremap ; :
" Q formats [selected] text
vmap Q gq
nmap Q gqap
" go over warped lines
nnoremap j gj
nnoremap k gk
" easier window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" hide search results
nmap <silent> <leader>/ :nohlsearch<CR>
" open mixed search
nnoremap <leader>. :CtrlPTag<CR>
" toggle tagbar
nnoremap <silent> <leader>b :TagbarToggle<CR>
" next/previous syntax error
nmap <silent> <leader>n :lnext<CR>
nmap <silent> <leader>p :lprev<CR>


" inputs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set bs=2                                    " Allow backspacing over everything
                                            " in insert mode
set ai                                      " Always set auto-indenting on
set softtabstop=4 shiftwidth=4 expandtab    " Each indentation level is four
                                            " spaces. Tabs are not used.
set mouse=a                                 " enable mouse support

" misc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible                            " Use Vim defaults (much better!)
set textwidth=72                            " standardzeilenlänge
set viminfo='20,\"500                       " Keep a .viminfo file.
set history=50                              " keep 50 lines of command history
set autowrite                               " Datei bei :next usw speichern
if filereadable("/etc/vim/vimrc.local")     " lokale vimrc falls vorhandne laden
  source /etc/vim/vimrc.local
endif

" path dependent settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd BufNewFile,BufRead ~/src/infoini/templates/* se tw=0 nowrap

