set nocompatible                            " Use Vim defaults (much better!)

" enable pathogen
call pathogen#infect()

" auto completion
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " ignore files on autocompletion
set wildignore+=*/build/*
set wildignore+=*/node_modules/*

" Display
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
colorscheme koehler                         " nicer colors
set list listchars=tab:»·,trail:·,extends:#
                                            " higlight extra whitespaces
set title                                   " change terminal title
set visualbell                              " blink on errors
syntax on                                   " enable syntax highlighting
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo,.pyc
                                            " ignore on auto completion
set so=5                                    " lines of context while scrolling
set ruler                                   " Show cursor position all the time
set foldmethod=syntax                       " fold blocks using syntax
set cursorline                              " underline line with cursor
highlight CursorLine   cterm=underline gui=underline guibg=NONE

" Search
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set hlsearch                                " highlight search results
set incsearch                               " search while typing
set ignorecase                              " 
set smartcase                               " override ic if uppercase letters

" underline misspelled words
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
hi clear SpellBad
hi SpellBad cterm=underline,bold ctermfg=red gui=undercurl,bold guifg=red

" mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader=","                           " set lead for custom bindings
" ,ev -> open vimrc
nmap <silent> <leader>ev :e ~/.vimrc<CR>
" while inserting toggle paste mode
set pastetoggle=<F2>
" ; also changes to command mode
nnoremap ; :
" go over warped lines
nnoremap j gj
nnoremap k gk
" easier window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" hide search results
nmap <silent> <leader>/ :nohlsearch<CR>
" open mixed search
nnoremap <leader>. :CtrlPTag<CR>
" toggle tagbar
nnoremap <silent> <leader>b :TagbarToggle<CR>
" next/previous syntax error
nmap <silent> <leader>n :lnext<CR>
nmap <silent> <leader>p :lprev<CR>
" format json
nmap <Leader>j :%!python -m json.tool<CR>
" format xml
nmap <Leader>x :%!xmllint --encode UTF-8 --format -<CR>
" open/close errors view
nmap <Leader>e :Errors<CR>
nmap <Leader>E :lclose<CR>

" inputs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set bs=2                                    " Allow backspacing over everything
                                            " in insert mode
set ai                                      " Always set auto-indenting on
set softtabstop=4 shiftwidth=4 expandtab    " Each indentation level is four
                                            " spaces. Tabs are not used.
set tabstop=4                               " tabs are 4 spaces
set mouse=a                                 " enable mouse support

" misc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set textwidth=72                            " standardzeilenlänge
set viminfo='20,\"500                       " Keep a .viminfo file.
set history=50                              " keep 50 lines of command history
set autowrite                               " Datei bei :next usw speichern
if filereadable("/etc/vim/vimrc.local")     " lokale vimrc falls vorhandne laden
  source /etc/vim/vimrc.local
endif
set directory=~/.cache,/var/tmp,/tmp

" path dependent settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd BufNewFile,BufRead ~/src/infoini/templates/* setl tw=0 nowrap
autocmd BufNewFile,BufRead ~/src/springlobby/src/* setl noexpandtab

" file type dependant settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd FileType html setl softtabstop=2 shiftwidth=2 tw=0
autocmd FileType rst setl spell spl=de
autocmd FileType coffee setl softtabstop=2 shiftwidth=2


" create directory on write
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if has("autocmd")
  autocmd BufWritePre * :silent !mkdir -p %:p:h
end

let g:syntastic_html_tidy_blocklevel_tags = [
\ 'md-toolbar',
\ 'md-sidenav',
\ 'md-content',
\ 'md-icon',
\ 'md-subheader',
\ 'md-divider',
\ 'md-input-container',
\ 'md-radio-group',
\ 'md-radio-button',
\ 'md-button',
\ 'md-switch',
\ 'md-list',
\ 'md-list-item'
\ ]


let g:syntastic_html_tidy_ignore_errors = [
\   'escaping malformed URI reference',
\   '<img> lacks "src" attribute',
\   'lacks "alt" attribute',
\   '"flex"',
\   '"ng-src"',
\   'proprietary attribute "ng-',
\   'proprietary attribute "layout',
\   '"layout"',
\   '"layout-align"'
\ ]
