#!/usr/bin/env bash
source /etc/profile
source ~/.profile

[ -f ~/.xsession.local ] && source ~/.xsession.local

export TERMINAL=roxterm

# start programms in background
numlockx &
pulseaudio -D &
xss-lock -v -- i3lock -c 000000 -d -e -n -i ~/.dotfiles/wallpaper/wallpaper.png &

xkbevd -bg &
setxkbmap us
xmodmap ~/.Xmodmap &
roxterm &
xset r rate 240 40 &
xset b 100 &

xkbevd -bg &

#xset m 3 1
#xset -b
#skype &

# set wallpaper
feh --bg-scale ~/.dotfiles/wallpaper/wallpaper.png

# start window manager
exec i3
