#!/bin/bash
source /etc/profile
source ~/.profile

export TERMINAL=roxterm

# start programms in background
numlockx &
pulseaudio -D &
xss-lock -v -- i3lock -c 000000 -d -e -n &

synergys &
xkbevd -bg &
setxkbmap us
xmodmap ~/.Xmodmap &
roxterm &
xset r rate 280 30 &
xset b 100 &

xkbevd -bg &

#xset m 3 1
#xset -b
#skype &

# linclude local
[ -f ~/.xsession.local ] && source ~/.xsession.local

# start window manager
exec i3
