#!/bin/bash
source /etc/profile
source ~/.profile

# start programms in background
numlockx &
pulseaudio -D &
#trayion &
synergys &
xkbevd -bg &
setxkbmap us
xmodmap ~/.Xmodmap &
roxterm &
xset r rate 280 30 &
xset b 100 &

xkbevd -bg &

#xset m 3 1
#xset -b
#skype &


# linclude local
[ -f ~/.xsession.local ] && source ~/.xsession.local

# start window manager
i3
