source ~/.zshrc.grml

if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi


## case-insensitive,partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# alias
alias ls='ls --color=auto -p'
alias grep='grep --color=auto'
alias cgrep='grep -r --include=\*.{cpp,h}'
alias g=git
alias lmap="nmap 192.168.0.0/24"
alias open="xdg-open"
alias psgrep='ps aux|grep -i'
alias c='python -ic "from __future__ import division; from math import *; from random import *"'
alias htserv='python -m SimpleHTTPServer 8000'
alias ec='emacsclient -nc'
alias kl='kubectl'
alias kx='kubectx'

alias -g G='|grep'
alias -g GR='|grep -iR'
alias -s log=vim
alias -s html=vim


# misc
unsetopt beep # kein beepen
setopt autocd # verzeichnis wechseln ohne cd
setopt extended_glob
setopt completeinword # autocompletion mitten im wort
disable -p '#' # don't treat # as pattern character

RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'


# history zeug
HISTFILE="$HOME/.zsh.history"
HISTSIZE=2000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # keine doppelten einträge
setopt hist_ignore_space    # spaces zusammenfassen
setopt inc_append_history   # befehl sofort in history anhängen

# fix "no matches found"
unsetopt nomatch



# farben
#promptinit
#prompt adam2


# editor
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line


# ssh agent handling from # http://stackoverflow.com/questions/18880024/start-ssh-agent-on-login
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initialising new SSH agent..."
    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi


# Virtualenv support

function virtual_env_prompt () {
    REPLY=${VIRTUAL_ENV+(${VIRTUAL_ENV:t}) }
}
grml_theme_add_token  virtual-env -f virtual_env_prompt '%F{magenta}' '%f'
zstyle ':prompt:grml:left:setup' items rc virtual-env change-root user at host path vcs percent

## ZLE tweaks ##

# use the vi navigation keys (hjkl) besides cursor keys in menu completion
bindkey -M menuselect 'h' vi-backward-char        # left
bindkey -M menuselect 'k' vi-up-line-or-history   # up
bindkey -M menuselect 'l' vi-forward-char         # right
bindkey -M menuselect 'j' vi-down-line-or-history # bottom


source <(kubectl completion zsh)  # setup autocomplete in zsh



test -e ~/.zshrc.local && source ~/.zshrc.local

if [ "$TERM" = "dumb" ]; then
    PS1="> "
fi

unset -f zed

# direnv hook
eval "$(direnv hook zsh)"
