#!/bin/bash

find cfgs/ -type f | while read SRC; do
    echo -ne "linking $SRC\t"
    TARGET=.${SRC##cfgs/}
    [ -e ~/$TARGET -a ! -L ~/$TARGET ] && echo "$TARGET is not a symlink" && return
    mkdir -p ` dirname ~/$TARGET`
    ln -sf  $PWD/$SRC ~/$TARGET && echo "OK" || echo "!!"
done
