[editor]
bufferline = "multiple"
end-of-line-diagnostics = "hint"
clipboard-provider = "wayland"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor.soft-wrap]
enable = true
