#!/bin/sh
rm -r ~/.local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/AppData/Local/Frontier\ Developments/Elite\ Dangerous/Options/Bindings
ln -sf "$PWD/Bindings" ~/.local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/AppData/Local/Frontier\ Developments/Elite\ Dangerous/Options/Bindings
