
.PHONY: wallpaper.jpg wallpaper.png
wallpaper.jpg:
	#wget -q -O wallpaper.jpg https://unsplash.it/3440/1440/?random
	#wget -q -O wallpaper.jpg https://source.unsplash.com/featured/3440x1440/?monochromatic

wallpaper.png:
	wget https://github.com/NixOS/nixos-artwork/blob/master/wallpapers/nix-wallpaper-waterfall.png?raw=true -O wallpaper.png
